notifications:
  email: false
git:
  quiet: true
  depth: 1
env:
  global:
    - TERM=dumb
language: java
jdk: openjdk8
install: true
jobs:
  include:
    # maven
    - stage: maven
      name: "Java 8"
      jdk: openjdk8
      script:
        - cd $TRAVIS_BUILD_DIR && ./mvnw clean test
    # gradle
    - stage: gradle
      name: "Java 8"
      jdk: openjdk8
      script: cd $TRAVIS_BUILD_DIR && ./gradlew clean test
cache:
  directories:
    - ~/.gradle
    - ~/.m2
