notifications:
  email: false
git:
  quiet: true
  depth: 1
language: java
jdk: openjdk8
install: true
env:
  global:
    - TERM=dumb
    - PROJECTS=("intro" "template")
jobs:
  include:
    - stage: openjdk8
      jdk: openjdk8
      name: "maven tests"
      before_script: for i in ${PROJECTS} ; do cp -Rfv $TRAVIS_BUILD_DIR/$i/src/test/resources/logback-maven.xml $TRAVIS_BUILD_DIR/$i/src/test/resources/logback.xml ; done
      script: cd $TRAVIS_BUILD_DIR && ./mvnw clean test
    - stage: openjdk8
      jdk: openjdk8
      name: "maven updates"
      script: cd $TRAVIS_BUILD_DIR && ./mvnw versions:display-property-updates
    - stage: openjdk8
      jdk: openjdk8
      name: "gradle tests"
      before_script: for i in ${PROJECTS} ; do cp -Rfv $TRAVIS_BUILD_DIR/$i/src/test/resources/logback-gradle.xml $TRAVIS_BUILD_DIR/$i/src/test/resources/logback.xml ; done
      script: cd $TRAVIS_BUILD_DIR && ./gradlew clean test
    - stage: openjdk8
      jdk: openjdk8
      name: "gradle updates"
      script: cd $TRAVIS_BUILD_DIR && ./gradlew dependencyUpdates -Drevision=release
cache:
  directories:
    - ~/.gradle
    - ~/.ivy
    - ~/.sbt
    - ~/.m2
